package-lock.json, src/modal/component/Modal/Modal.styles.ts, src/modal/component/Modal/Modal.tsx, src/state/State.ts, src/types/Options.ts
When we initialize the wallet-selector now we can the walletSelectorUI object (option) to optionally render elements in `modal.`
```
walletSelectorUI: {
description: string,
explanation: string,
}
```
```
const near = new NearWalletSelector({
wallets: ["nearwallet", "senderwallet", "ledgerwallet", "mywallet"],
networkId: "testnet",
theme: "light",
walletSelectorUI: {
description: 'Please select a wallet to connect to this dapp (custom-desc):',
explanation: 'Explain what is a wallet here...',
}
});
```
=> Optionally render wallet explanation and set default description

src/controllers/WalletController.ts, src/wallets/browser/NearWallet.ts
This PR includes:
- Bug fix when dapp user clicks the Near Wallet option and then navigates back to the dapp  does not crash anymore.
- Update state properly for Near Wallet on page load.
=> Bug fixed when dapp user cancels sign in and navigates back

src/modal/Modal.tsx, src/wallets/injected/SenderWallet.ts
- Improvement on network change for sender wallet.
- When network id changes in sender wallet, we display the "You must change networks" in the modal.
=> Improve Network Changes in SenderWallet

README.md, example/src/App.js, example/src/index.js, src/controllers/WalletController.ts, src/core/NearWalletSelector.tsx, src/index.ts, src/state/State.ts, src/types/EventList.ts, src/types/State.ts, src/utils/__tests__/EventEmitter.spec.ts, src/wallets/browser/NearWallet.ts, src/wallets/injected/SenderWallet.ts
- Reverted back to instantiating the `NearWalletSelector` class.
- Moved `WalletConnection` logic into `NearWallet` class.
- Updated example project.
- Updated README to reflect API changes.
- Fixed regression in #100 where there was an old `state.walletProviders` reference which caused the `init` wallet method to fail when previously logged in.
=> #115 Migrate Async Init

example/src/App.js, src/interfaces/InjectedSenderWallet.ts, src/wallets/injected/SenderWallet.ts
- Listen to the onAccountChanged event emited by Sender Wallet
- If the current selected account is not signed in prompt user to connect dApp with the newly selected account.
- If user rejects fire event "disconnect" to inform dApp
- Fixed typo in example dApp when listening on the `"disconnect"` event.
I tried many different ways to handle the case when user rejects (closes the sender wallet popup window) during the process when a new account is selected inside the Sender Wallet the best I could come up was to call the `disconnect`in which case the dApp sets account to null.
=> Handle account change in Sender Wallet

examples/angular/package.json, examples/angular/yarn.lock
- Typescript version  "~4.5.2" added as a devDependency.
The angular example works on the current location just fine.
With this PR I am trying to address the possibility when someone copies this example somewhere outside the location `"wallet-selector/examples/angular"`.
I noticed that after running `"yarn start"` angular cli can't find typescript module if it is outside the wallet-selector folder.
=> Fix typescript missing dependency in Angular Example

src/interfaces/InjectedSenderWallet.ts, src/wallets/injected/SenderWallet.ts
Fixes: #157 
Due to the recent Sender API change (as documented here: https://docs.senderwallet.io/api-reference/near-provider-api), `near-wallet-selector` needs to be updated to work well with the latest version. 
A relevant idea is to maintain versioned implementations which could be loaded, by detecting the version of the installed extension wallet, but this is not high-priority since we prefer to standardize and stabilize the wallet SDKs.
=> feat: sender wallet API change

README.md, examples/angular/src/app/app.component.ts, examples/react/src/App.tsx, examples/vue/src/App.vue, src/controllers/WalletController.ts, src/core/NearWalletSelector.tsx, src/modal/Modal.tsx, src/wallets/Wallet.ts, src/wallets/hardware/LedgerWallet.ts
- `signIn` now takes hardware wallet specific parameters, removing the need for additional state in `LedgerWallet` and `setAccountId` and `setDerivationPath`.
- Updated README to reflect changes.
- Exported library to the `window` in each example for "headless" testing such as this `signIn` method.
=> #173 Unify Sign In Functionality Across Wallets

README.md, examples/angular/src/app/app.component.ts, examples/angular/src/config.ts, examples/react/src/App.tsx, examples/react/src/config.ts, examples/vue/src/App.vue, examples/vue/src/config.ts, src/config.ts, src/controllers/WalletController.ts, src/core/Contract.ts, src/core/NearWalletSelector.tsx, src/index.ts, src/interfaces/Options.ts, src/modal/Modal.tsx, src/wallets/Wallet.ts, src/wallets/browser/NearWallet.ts, src/wallets/injected/SenderWallet.ts
- Renamed `walletSelectorUI` to `ui` and made it optional.
- Moved `theme` into `ui`.
- Removed configuration for `explanation`. I'm not sure there's really a use case for this to be customisable at this point in time. We can easily add it back in the future (without triggering a breaking change) if this assumption is wrong.
- Switched `contract.viewMethods` & `contract.changeMethods` for `contract.methodNames`. This is now passed as part of `signIn` to configure the access key.
- Renamed `contract.accountId` to `contract.contractId` to maintain consistency seen in `near-api-js` and Sender Wallet.
- Renamed `getAccountId` to `getContractId` on the Contract class.
- Added an "Options" section in the README to cover the various customisable properties.
- Simplified configuration of README …
=> Options Refactor

src/modal/Modal.styles.ts
- Fix: text color is now applied properly when no theme is provided in options.
Since it was just 1 commit I did not open an issue for it.
The problem was when no theme is provided and the OS/Browser is configured to use system's Light mode then the text color was not applied properly, and also the border of buttons was not applied properly.
=> Fix UI text and border colors

src/interfaces/InjectedSenderWallet.ts, src/wallets/injected/SenderWallet.ts
- Corrected `responses` property to `response`. This was causing `signAndSendTransaction` to fail when successful.
=> Fix Sender Wallet Interface

.eslintrc.js, src/interfaces/Promisify.ts, src/services/logging.service.ts
- Fixed debug mode on by default. It's now opt-in by default.
- Added `@typescript-eslint/array-type` ESLint rule to standardise array types.
=> Fix Debug Logging

packages/near-wallet-selector/src/wallets/browser/NearWallet.ts
Refactored `getWalletUrl` logic. We now default to testnet for unknown `networkId` values. As the TODO states, this will become an error case once we've migrated NEAR Wallet to its own package.
=> fix: [SQAC-101] Fix NEAR Wallet walletUrl Resolution

packages/near-wallet-selector/README.md, packages/near-wallet-selector/src/core/NearWalletSelector.tsx
Added support for passing a `receiverId` to `signAndSendTransaction`.
=> feat: [SQAC-103] Support for Ad Hoc Smart Contract Calls

packages/near-wallet-selector/package.json, packages/near-wallet-selector/project.json
- Fixed bug where `dependencies` were incorrectly added to `devDependencies` in the build output.
- Updated version to `3.0.0-alpha.1`.
=> chore: Fix Nx Dependency Configuration

packages/ledger-wallet/src/lib/ledger-wallet.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/near-wallet/src/lib/near-wallet.ts, packages/sender-wallet/src/lib/sender-wallet.ts, packages/wallet-connect/src/WalletConnect.ts
After changing the baseHref in examples the images stopped showing up.
Changing the path to an icon from absolute to relative fixes this issue.
=> fix: Made icon paths relative

examples/angular/src/app/components/content/content.component.html, examples/angular/src/app/components/content/content.component.ts, examples/react/src/components/Content.tsx, packages/core/README.md, packages/core/src/index.ts, packages/core/src/lib/NearWalletSelector.tsx, packages/core/src/lib/Optional.ts, packages/core/src/lib/wallet/index.ts, packages/core/src/lib/wallet/transactions.ts, packages/core/src/lib/wallet/wallet.ts, packages/ledger-wallet/src/lib/ledger-wallet.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/near-wallet/src/lib/near-wallet.ts, packages/sender-wallet/src/lib/injected-sender-wallet.ts, packages/sender-wallet/src/lib/sender-wallet.ts, packages/wallet-connect/src/lib/wallet-connect.ts
- Added support for `signAndSendTransactions` for NEAR Wallet and Sender.
- Modified other wallets to throw an error for now.
- Exposed a serialisable version of `Transaction` (similar to `Action`).
- Added a `Optional` type helper to make properties on an interface optional in a similar approach you see with helpers like `Pick` and `Omit`.
- Updated examples to include a simple demo.
- Corrected interfaces for signing methods on `BrowserWallet`.
Closes #164
=> feat: #164 Support for Multiple Transactions (NEAR Wallet & Sender)

.eslintignore
Fixed `yarn lint`  not detecting lint errors for the `packages`.
Removed `lib/`  from `.eslintignore` file because all the packages have a `lib` directory which in the end was being ignored.
Closes # (issue) No issue has been opened for this PR.
=> fix: Fix eslint for packages

packages/wallet-connect/src/lib/wallet-connect.ts
Inside the wallet-connect.ts file the signAndSendTransactions was not implemented. I implemented the logic to handle multiple transactions using the WalletConnect wallet.
=> feat: Finished signAndSendTransactions method

packages/math-wallet/src/lib/math-wallet.ts
- Fixed bug in `getAccounts` method when assigning the value for `accountId`.
=> fix: SQAC-119 Bug Fix for getAccounts in Math Wallet

packages/core/src/lib/modal/Modal.tsx
If you want to connect using the Ledger Wallet and you type in an account id that is not registered with the public key an error will not be shown. There will not be any UI changes or messages to inform you that something went wrong.
This is happening because after we update the `ledgerError` state variable we also reset the state using the `resetState` method.
Now the `resetState` method will only be called when `state.showModal` changes using the `useEffect` hook.
=> fix: Fixed bug where error was not shown when connecting with ledger

examples/react/src/contexts/WalletSelectorContext.tsx, packages/sender/src/lib/sender.ts
Make wallet-selector work with Sender v0.2.3. 
The issue is that, when using Sender, `window.near.isSignedIn()` is  `false` when you refresh the page (which will be `true` after a while, e.g. 300ms). We also noticed the similar issue in MetaMask that `window.ethereum.isConnected()`  is `false` when the page is reloaded, which will become `true` within 1s. This seems to be a limitation of Chrome extension since the extension needs to update the data from background.
=> fix: wait 300ms if necessary when initialize sender instance

README.md
Sender `0.2.3` has now fixed the bug around persisting the signed in state.
=> docs: Remove Known Issues Section

packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.ts
- Improved the message error on alert by showing the type of the error
From our current implementation what we can do is to improve the message so the dApp user can understand (have more info) on why they can’t signIn with this wallet because signIn is requested by the modal it’s not possible to catch the error outside of it.
Closes #251
=> fix: SQAC-122 Improve Sender Error when requestSignIn Fails

README.md, package.json, packages/core/package.json, packages/ledger/package.json, packages/math-wallet/package.json, packages/near-wallet/package.json, packages/sender/package.json, packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.ts, packages/wallet-connect/package.json
- Bumped version to `3.0.1` (#258).
- Improved Sender error when `requestSignIn` fails (#255).
=> v3.0.1 Release (dev -> main)

packages/core/src/lib/options.ts, packages/core/src/lib/options.types.ts, packages/core/src/lib/wallet-selector.ts, packages/core/src/lib/wallet-selector.types.ts
Now developers can add a `debug: true` property to the options when initializing the wallet selector and it will let them debug using the logger.
=> feat: Resolved conflicts

package.json, packages/core/package.json, packages/ledger/package.json, packages/math-wallet/package.json, packages/near-wallet/package.json, packages/sender/package.json, packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.ts, packages/wallet-connect/package.json
Sender has been updated yesterday and they have introduced a breaking change.
Previously `near.signOut()` returned `boolean` but now it is an `async` function which returns a promise which in the end resolves either `true `value or an `error` object.
This PR fixes the `signOut `for sender
=> fix: sender signout bug

packages/core/src/lib/modal/components/Modal.styles.ts, packages/core/src/lib/modal/components/WalletOptions.tsx
Disabled wallet options while in progress of connecting to a wallet.
=> feat: Disabled wallet option while connecting

packages/core/src/lib/modal/components/AlertModal.tsx, packages/core/src/lib/modal/components/Modal.styles.ts, packages/core/src/lib/modal/components/Modal.tsx, packages/core/src/lib/modal/components/WalletOptions.tsx
Instead of using the `alert()` function I created a custom component and state to show and hide custom alert box on errors.
=> feat: Replaced alert with custom modal

packages/sender/src/lib/sender.ts
- Cleanup and emit disconnected when switching between accounts in Sender extension.
- Emit connected if there are existing accounts for sender.
=> fix: Handle accountChanged for Sender

packages/ledger/src/lib/ledger.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/wallet-utils/src/lib/sign-transactions.ts
- Added missing `networkId` parameter when calling `signTransaction`.
- Added missing `signerId` for `transformTransactions`.
- Fixed `networkId` parameter for `getPublicKey` incorrectly receiving `nodeUrl`.
=> fix: `signTransactions` Improvements

packages/ledger/project.json, packages/math-wallet/project.json, packages/near-wallet/project.json, packages/sender/project.json, packages/wallet-connect/project.json, packages/wallet-utils/project.json
This PR is addresses the issue with some of the frameworks which don't transpile ES6 modules outside the projects /src folder.
By changing the builder to `@nrwl/web:rollup` we align all the packages to provide support for (esm, cjs, umd) like `core` and `modal-ui`
- Changed builder builder to @nrwl/web:rollup
- Added formats `"format": ["esm", "umd", "cjs"]` option.
=> build: Change Builder to Support (esm, cjs, umd)

packages/core/src/lib/wallet-selector.ts, packages/modal-ui/src/lib/modal.tsx
- Calling `setupWalletSelector` and `setupModal` now returns the same instance each time which is stored in memory.
=> refactor: Sqac 149 prevent side effects of multiple calls to setup modal setup wallet selector

packages/modal-ui/src/lib/components/DerivationPath.tsx, packages/modal-ui/src/lib/components/styles.css
- Added Support Multiple Derivation Paths in UI.
=> feat: Support Multiple Derivation Paths in UI

packages/math-wallet/src/lib/injected-math-wallet.ts, packages/math-wallet/src/lib/math-wallet.ts
Cleaned up our patch around `MathAccount` now it's been fixed in the latest update from Math Wallet.
=> refactor: Math Wallet Update

packages/core/src/lib/options.spec.ts, packages/core/src/lib/options.ts, packages/core/src/lib/options.types.ts, packages/ledger/src/lib/ledger.ts
- Added extra option `indexerUrl` to fix bug for ledger when we query accounts by public key.
Closes #321
=> fix: Add `indexerUrl` to Network

packages/core/README.md, packages/core/src/lib/options.spec.ts, packages/core/src/lib/options.ts, packages/core/src/lib/options.types.ts, packages/my-near-wallet/README.md, packages/near-wallet/src/lib/near-wallet.ts, packages/wallet-connect/src/lib/wallet-connect.ts
- Removed `betanet` network preset.
=> refactor: Remove `betanet` Network Preset

README.md, packages/core/README.md, packages/core/package.json, packages/ledger/README.md, packages/ledger/package.json, packages/math-wallet/README.md, packages/math-wallet/package.json, packages/meteor-wallet/README.md, packages/meteor-wallet/package.json, packages/my-near-wallet/README.md, packages/my-near-wallet/package.json, packages/nightly-connect/README.md, packages/nightly-connect/package.json, packages/nightly/README.md, packages/nightly/package.json, packages/sender/README.md, packages/sender/package.json, packages/wallet-utils/README.md, packages/wallet-utils/package.json
- Added `"near-api-js": "^0.44.2"` as a `peerDependency` for the packages which use it directly.
- Solves the first problem reported in this issue: https://github.com/near/wallet-selector/issues/349
=> fix: Set near-api-js as Peer Dependency

packages/ledger/src/lib/ledger.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/nightly-connect/src/lib/nightly-connect.ts, packages/nightly/src/lib/nightly.ts
To avoid nonce increment issues and a concept called “transaction dependency relationship“, we need to move away from using Promise.all when sending transactions in the following wallets:
- Ledger
- Math Wallet
- Nightly
- Nightly Connect
=> fix: Send Transactions in Series

packages/ledger/README.md
- Added known issues section to note down potential error `Device is already open` for ledger.
- Addreses second problem reported in this issue https://github.com/near/wallet-selector/issues/349
Closes #349
=> docs: Improve Ledger Docs

packages/ledger/src/lib/ledger.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/meteor-wallet/src/lib/meteor-wallet-types.ts, packages/meteor-wallet/src/lib/meteor-wallet.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts, packages/near-wallet/src/lib/near-wallet.ts, packages/nightly-connect/src/lib/nightly-connect.ts, packages/nightly/src/lib/nightly.ts, packages/sender/src/lib/sender.ts, packages/wallet-connect/src/lib/wallet-connect.ts
Added optional `deprecated?: boolean` flag as configurable setup option for all wallets. By default its false.
=> fix: Added deprecated flag as configurable setup option

packages/modal-ui/src/lib/components/DerivationPath.tsx, packages/modal-ui/src/lib/components/HardwareWalletAccountsForm.tsx, packages/modal-ui/src/lib/components/styles.css
The reason for this refactoring and switching to a single derivation path with multiple account id(s) is to simplify the UI/UX and apparently this is a common use case in the ecosystem from the feedback we've got in the last calls with NEAR.
- Added support to select a single derivation path.
- Select one or multiple account id(s) for the chosen derivation path.
- Added fallback when indexer service fails (provide account id manually).
=> refactor: Support Single Derivation Path with Multiple Account Id-s

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/general.md, .github/PULL_REQUEST_TEMPLATE/wallet_integration.md
- Added a second PR template specifically for wallet integrations.
- Removed break changes checklist due to various bugs in the automation around it.
- Merging into `dev` won't update the existing templates. It's only once it's in `main` that they'll take effect.
=> chore: Support for Multiple PR Templates

packages/core/src/lib/wallet/wallet.types.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts
- Fixes the case when a transaction without a deposit returns undefined.
- By default transactions with a deposit redirect to MyNearWallet to approve/reject transaction.
=> fix: Return the result of signAndSendTransaction for MyNearWallet (dev).

packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- Fix `wallet-selector` initialization when a user was previously `signedIn` via an injected wallet but later on removed that wallet
- Wallet Selector now clears the signed in state.
Closes #388
=> fix: Improve Wallet Selector Initialization

packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.ts
The PR is to fix the incompatible `signAndSendTransaction` response type with Sender v1.0.0 and later version. 
Closes #392
=> fix: `signAndSendTransaction(s)` response type change in Sender wallet

examples/angular/src/app/components/content/content.component.html, examples/angular/src/app/components/content/content.component.ts, examples/react/components/Content.tsx, packages/core/docs/api/wallet.md, packages/core/src/index.ts, packages/core/src/lib/wallet/wallet.types.ts, packages/ledger/src/lib/ledger.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/meteor-wallet/src/lib/meteor-wallet.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts, packages/nightly-connect/src/lib/nightly-connect.ts, packages/nightly/src/lib/nightly.ts, packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.ts, packages/wallet-connect/src/lib/wallet-connect.ts
- Added support for `verifyOwner` to the API of all wallet integrations.
- On MyNearWallet  this feature is only supported on **testnet**
- On Sender this feature works only when Sender is unlocked.
- Other wallets throw a "Method not supported" error.
The work for this PR initially started here: #320, there were some build issues that I was unable to solve quickly, I copied everything from there and addressed requested changes here in separate commits.
Closes #318.
=> feat: Add Support for verifyOwner

packages/modal-ui/src/lib/components/HardwareWalletAccountsForm.tsx, packages/modal-ui/src/lib/components/Modal.tsx, packages/modal-ui/src/lib/components/styles.css
This PR addresses the issue when css class names of the `modal-ui` conflict with some class names from the [Bootstrap Framework](https://getbootstrap.com/) this is a continuation of the work started here:  https://github.com/near/wallet-selector/pull/416
This PR renames these css classes:
- `.modal`  to  `.nws-modal`
- `.modal-header`  to  `.nws-modal-header`
- `.modal-body` to `.nws-modal-body`
- `.form-control` to `.nws-form-control`
Closes #415
=> fix: Add Prefix to css class names which conflict with Bootstrap

README.md, examples/angular/src/app/app.component.ts, examples/react/contexts/WalletSelectorContext.tsx, package.json, packages/nightly-connect/README.md, packages/nightly-connect/src/lib/nightly-connect.ts, scripts/nightly-connect-client.ts, yarn.lock
Changes:
- addition of flow when previous session is persisted by Nightly Connect client (previous session will be remembered when app will be closed and opened one again)
- persisting public key and account id for Nightly Connect session until disconnect
=> fix: Nightly Connect - proper session persisting

package.json, packages/meteor-wallet/src/lib/meteor-wallet.ts
Added support to Meteor Wallet for the `verifyOwner()` method. As recently added in #391
=> feat: [Meteor] Support for verifyOwner method

examples/angular/src/styles.scss, packages/modal-ui-js/project.json, packages/modal-ui-js/tsconfig.json
- Changed bundler to rollup to support ESM and CJS for `modal-ui-js` .
=> Change Bundler To Rollup Support (esm and cjs)

packages/coin98-wallet/package.json
The reason we need to set `near-api-js` as a **peerDependency** for `Coin98 Wallet` is that there can be issues and version **mismatches** between the version of `near-api-js` in Wallet Selector and in dApps which causes some weird behavior where transactions might fail due to serialization issues.
=> fix: Set `near-api-js` as peerDependency for `Coin98 Wallet`

packages/meteor-wallet/src/lib/meteor-wallet.ts
This removes the code in Meteor Wallet's implementation which threw an error when `signerId` wasn't present inside transactions. This matches other wallet implementations- the old code was causing issues with some integrations.
=> fix: [Meteor] allow "signerId" to be optional in transactions

packages/here-wallet/src/lib/here-wallet.ts, packages/here-wallet/src/lib/utils.ts, packages/meteor-wallet/src/lib/meteor-wallet.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts, packages/wallet-connect/src/lib/wallet-connect.ts
- This PR removes the `cleanup()` method or the calls to `keystore.clear()` method, now LAK is kept in the local storage after signOut too.
=> fix: Avoid deleting LAK on signOut from local keystore

packages/neth/src/lib/neth.ts, packages/welldone-wallet/src/lib/welldone.ts
- WELLDONE and NETH wallets will not show on mobile anymore. They are injected wallets.
=> fix: Removed welldone and neth wallet from mobile

packages/core/src/lib/locale/ko.json, packages/core/src/lib/translate/translate.ts
Add Korean translation option, following the instructions [here](https://github.com/near/wallet-selector/blob/dev/packages/core/docs/guides/multilanguage-support.md#adding-new-language).
Because the word ordering in English and Korean are different, I left some parts untranslated. I don't think it will prevent comprehension, though.
=> feat: add Korean translations

packages/modal-ui/src/lib/components/LanguageSelector.tsx
While adding the Bulgarian translation I noticed Korean is missing from the LanguageSelectorComponent Maybe a guide of few lines on the README for translation contributors will help
=> fix: add Korean to the LanguageSelector

packages/modal-ui/src/lib/modal.tsx
=> fix: Multiple modal containers instead of one fixed

README.md, packages/welldone-wallet/README.md, packages/welldone-wallet/src/lib/welldone.ts
WELLDONE Wallet has an update to v0.1.0 , and have some changes in method name. 
* `dapp:sign` -> `dapp:signTransaction`
* currently not support signMessage, so comment the `verifyOwner` code. But we will support `dapp:signMessage` in recent days.
* refactoring `signAndSendTransactions` method to use `signTransactins` function in `packages\wallet-utils\src\lib\sign-transactions.ts` to avoid using helper function.
* rename `Welldone` to `WELLDONE` in some readme files.
=> refactor: method name change in WELLDONE Wallet

package.json, packages/here-wallet/src/lib/selector.ts, yarn.lock
Implement signMessage Standart for HERE Wallet
Standart draf: https://github.com/near/NEPs/pull/413
`signMessage` sign hash of `NEP0413:` + `{"message":"hi","nonce":[0,...,31],"receiver":"myapp.com"}` string by full access key and return signature, then verifies the signature and verifies that the public key is indeed the full access key on the blockchain.
If verification fails, the method returns an error.
=> here-wallet: add signMessage

packages/welldone-wallet/src/lib/welldone.ts
WELLDONE Wallet has an update to v0.1.1 , and now support `signMessage`.
So I added `verifyOwner` method to `welldone.ts`.
=> feat: add verifyOwner to WELLDONE wallet

examples/angular/src/app/app.component.ts, examples/react/contexts/WalletSelectorContext.tsx, packages/here-wallet/src/lib/index.ts, packages/modal-ui-js/README.md, packages/modal-ui-js/src/lib/components/GetAWallet.ts, packages/modal-ui-js/src/lib/modal.types.ts, packages/modal-ui-js/src/lib/render-modal.ts, packages/modal-ui/README.md, packages/modal-ui/src/lib/components/Modal.tsx, packages/modal-ui/src/lib/components/WalletHome.tsx, packages/modal-ui/src/lib/modal.types.ts
- Added optional `onHide` callback method to ModalOptions.
- The method gets triggered only when user clicks the close button or the overlay.
=> feat: Add optional `onHide` callback method in modal options

packages/core/README.md, packages/core/src/lib/wallet-selector.ts, packages/core/src/lib/wallet-selector.types.ts
- Optionally pass the `allowMultipleSelectors` option in `setupWalletSelector`.
```ts
await setupWalletSelector({
allowMultipleSelectors: true, // Wallet selector will not act as singleton, a new instance of the selector will be returned.
network: "testnet",
debug: true,
modules: [setupNearWallet()],
})
```
=> feat: Optionally allow creating new wallet selector instances.

examples/angular/src/app/app.component.ts, examples/angular/src/app/components/content/content.component.ts, examples/react/contexts/WalletSelectorContext.tsx, examples/react/contexts/WalletSelectorExportContext.tsx, packages/core/src/index.ts, packages/modal-ui-js/README.md, packages/modal-ui-js/docs/api/modal.md, packages/modal-ui-js/src/index.ts, packages/modal-ui-js/src/lib/components/LedgerAccountsOverviewList.ts, packages/modal-ui-js/src/lib/modal.ts, packages/modal-ui-js/src/lib/modal.types.ts, packages/modal-ui-js/src/lib/render-modal.ts, packages/modal-ui/README.md, packages/modal-ui/docs/api/modal.md, packages/modal-ui/src/index.ts, packages/modal-ui/src/lib/components/Modal.tsx, packages/modal-ui/src/lib/modal.tsx, packages/modal-ui/src/lib/modal.types.ts
- This PR is to address the #661 issue.
- Added `EventEmitter` and internally emitting `onHide` event with the reason being either `user-triggered` or `wallet-navigation`
- Ability to listen to the event by `modal.on("onHide", ({ hideReason }) => { console.log(hideReason) })`
- Removed references of the old `onHide` callback through the ModalOptions to avoid confusion and since we're not invoking that method anymore.
=> feat: Add EventEmitter and listen to events through modal instance

package.json, packages/account-export/src/lib/helpers/importAccount.spec.ts, packages/account-export/src/lib/helpers/importAccount.ts, yarn.lock
Fixes #680 
This PR contains implementation for changing `generateSecretKey` interface of account-export.
1. Removed  `generate-password` package
2. Update `generateSecretKey` to use `tweetnacl.randomBytes`
3. Minor update on `importAccount.spec` tests
=> fix: Update generateSecretKey from account-export package

CONTRIBUTING.md, README.md, examples/angular/src/app/pages/wallet-selector-export/wallet-selector-export.component.ts, examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts, examples/react/contexts/WalletSelectorContext.tsx, examples/react/contexts/WalletSelectorExportContext.tsx, packages/default-wallets/README.md, packages/default-wallets/src/lib/default-wallets.ts
- Removed the `setupMyNearWallet()` and `setupLedger()` from `@near-wallet-selector/default-wallets`.
- The `@near-wallet-selector/default-wallets` will not return any wallets by default and should probably be deprecated in the next version.
- Removed references of `default-wallets` from the project/repo.
=> refactor: Remove wallets from default-wallets list

packages/core/README.md, packages/core/docs/api/selector.md, packages/core/src/lib/options.ts, packages/core/src/lib/options.types.ts, packages/core/src/lib/wallet-selector.types.ts, packages/modal-ui-js/src/lib/modal.ts, packages/modal-ui-js/src/lib/render-modal.ts, packages/modal-ui/src/lib/components/WalletOptions.tsx
- Added `randomizeWalletOrder` option in `setupWalletSelector` to optionally randomize the order of wallets in the **More** section of the Modal UI.
=> feat: Randomize wallet list

packages/welldone-wallet/src/lib/welldone.ts
Add support for `buildImportAccountsUrl` in WELLDONE Wallet.
We also implemented the `importAccountsInSecureContext` method, but we decided to use the `buildImportAccountsUrl` for now because there is a little problem when calling the method without creating a wallet. If we solve the problem before the wallet-migration event starts, we plan to use the `importsAccountsInSecureContext` method.
=> feat: add account-export for WELLDONE

packages/modal-ui/src/lib/components/Modal.tsx, packages/modal-ui/src/lib/components/WalletConnected.tsx, packages/sender/src/lib/sender.ts
- Fixed eslint warnings on modal-ui.
- Avoid throwing an error when `getPublicKey` is not available in the `signer` of the Sender wallet.
- Fixes the case when the user is logged in but the wallet gets locked then the user gets signed out on the next page refresh, trying to sign in again would show the below error:
=> fix: Check whether getPublicKey is available in sender.

packages/modal-ui/src/lib/components/DerivationPath.tsx
- Fixed the bug in the ledger in the Overview Account List view of `modal-ui` to immediately populate the `selectedAccounts` when only one account is found.
=> fix: Fix overview account list UI for Ledger

packages/coin98-wallet/src/lib/coin98-wallet.spec.ts, packages/coin98-wallet/src/lib/coin98-wallet.ts, packages/coin98-wallet/tsconfig.json, packages/finer-wallet/src/lib/finer.spec.ts, packages/finer-wallet/src/lib/injected-wallet.ts, packages/finer-wallet/tsconfig.json, packages/ledger/src/lib/ledger.spec.ts, packages/math-wallet/src/lib/injected-math-wallet.ts, packages/math-wallet/src/lib/math-wallet.spec.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/math-wallet/tsconfig.json, packages/meteor-wallet/src/lib/meteor-wallet.spec.ts, packages/meteor-wallet/tsconfig.json, packages/my-near-wallet/src/lib/my-near-wallet.spec.ts, packages/narwallets/src/lib/narwallets.spec.ts, packages/narwallets/tsconfig.json, packages/opto-wallet/src/lib/opto-wallet.spec.ts, packages/sender/src/lib/injected-sender.ts, packages/sender/src/lib/sender.spec.ts, packages/sender/src/lib/sender.ts, packages/sender/tsconfig.json, packages/welldone-wallet/src/lib/injected-welldone.ts, packages/welldone-wallet/src/lib/welldone.spec.ts, packages/welldone-wallet/tsconfig.json
`sender.spec.ts` doesn't work. I am not getting any errors so I am not sure how to fix it. I need some help with it.
=> Test coverage

packages/account-export/src/lib/components/ExportAccount.tsx, packages/core/src/lib/services/provider/provider.service.spec.ts, packages/core/src/lib/services/provider/provider.service.ts, packages/ledger/src/lib/ledger-client.spec.ts, packages/ledger/src/lib/ledger-client.ts, packages/ledger/src/lib/ledger.ts, packages/meteor-wallet/src/lib/meteor-wallet.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts, packages/nightly-connect/src/lib/nightly-connect.ts, packages/nightly/src/lib/nightly.ts, packages/opto-wallet/src/lib/opto-wallet.ts, packages/wallet-connect/src/lib/wallet-connect.ts, packages/wallet-utils/src/lib/create-action.ts, packages/wallet-utils/src/lib/sign-transactions.ts, packages/welldone-wallet/src/lib/welldone.ts
This PR is about fixing the way we import modules from `near-api-js`.
In our packages we import code from NAJ in this way:
```ts
import { providers, utils } from "near-api-js";
```
Although this is not necessarily “wrong” there are no linting or build errors and when our packages are installed via npm/yarn everything seems to work just fine.
The problem shows up when the CDN link is used in a dApp to import our packages.
From more investigation, it was found that NAJ does not export named modules at the top level for `accountCreator, providers, utils, transactions, validators, multisig` somewhere in the code everything is first imported as an alias and then exported:
```ts
import * as providers from './providers';
import * as utils from './utils';
export { providers, utils };
```
So in …
=> fix: Fix imports from near-api-js

packages/modal-ui-js/src/lib/modal.types.ts, packages/modal-ui-js/src/lib/render-modal.ts, packages/modal-ui/src/lib/modal.types.ts
Removed unused `onHide` property from modal options.
=> refactor: Removed unused onHide property from modal options

examples/react/components/ExportContent.tsx, examples/react/contexts/WalletSelectorContext.tsx, examples/react/contexts/WalletSelectorExportContext.tsx
- Removed `null` type from the `modal` and `selector` in `WalletSelectorContextValue` to avoid using the `!` everywhere in child components.
=> refactor: Revert type changes in `WalletSelectorContextValue` interface in react example

packages/neth/.eslintrc.json, packages/neth/src/lib/neth-lib.ts
- This PR just properly disables the eslint rules that are in `neth-lib.ts` at the top of the file, so in the future PR's these warnings would not show:
=> chore: Disable rules from eslintrc.json config for neth-lib.ts file

packages/core/README.md, packages/core/docs/api/selector.md, packages/core/src/lib/options.ts, packages/core/src/lib/options.types.ts, packages/core/src/lib/wallet-selector.types.ts
Adds a new option, `relayerUrl`, to the wallet-selector configuration options.  This option is passed down to wallet modules so that wallets that support submitting meta transactions can do so based on its presence.
=> Add relayerUrl to configuration options

package.json, yarn.lock
- Bump version for `@here-wallet/core` to fix breaking changes from the upgrade of `near-api-js`.
Fixes issue during signIn:
=> fix: Fix signIn for HERE Wallet

packages/core/docs/api/selector.md, packages/core/src/lib/wallet-selector.types.ts
- Added `WalletSelectorParams` jsdoc descriptions
- Added `allowMultipleSelectors` missing doc
=> docs: Added additional jsdoc descriptions and missing doc

package.json, yarn.lock
Chasing some serialization issues with borsh, and it looks like our yarn.lock here may have been causing 2 different versions of NAJ to load -- this bumps the entry in the yarn.lock to the current version of NAJ
=> Bump peerDep NAJ to 2.1.3

package.json, yarn.lock
- Bumped this dependency manally since dependabot got "confused" once the `@walletconnect/sign-client` was merged and the other original PR was closed https://github.com/near/wallet-selector/pull/795
=> chore: Bump @walletconnect/types from 2.5.2 to 2.7.2

examples/react/contexts/WalletSelectorExportContext.tsx, packages/account-export/src/lib/components/ExportAccount.tsx, packages/account-export/src/lib/index.types.ts
This PR contains minor change on the structure of onComplete props from 
Array<string> to { accounts: Array<string> , walletName string}
As outcome, console.log on example should be similar to:
=> feat: Updated the onComplete props structure on export account

package.json, packages/account-export/project.json, yarn.lock
- Bumped version for `ngx-deploy-npm` and added the `deploy` script for `account-export` package.
=> chore: Bump version for ngx-deploy-npm from 4.3.10 to 7.0.1

.github/workflows/bump-version.yml
- Fix the case when the next version is not detected correctly and it falls back to `0.0.0`
=> ci: Fix detection of the next version

examples/angular/project.json
=> fix: Disable buildOptimizer for Angular Example

packages/sender/src/lib/sender.ts
This PR changes logic and the waiting time for the `isSignedIn()` for Sender Wallet the details can be found here https://github.com/near/wallet-selector/issues/944#issuecomment-1735551406
- This waiting time gets triggered only when some other extensions mentioned in the above comment block the Sender wallet from somehow updating the `isSignedIn()` state this means if these extensions are not installed or the user is not signed in the wallet selector there will be no waiting time.
Closes: #944
=> refactor: Change the logic for waiting about the isSignedIn() in Sender

.github/release-drafter.yml
This PR adds the option to exclude specific PRs from the Draft Release notes.
Label added: 
Closes: #951
=> ci: Exclude PRs by label from release-drafter notes.

examples/angular/src/app/components/content/content.component.ts, examples/react/components/Content.tsx
=> feat: Added verify for the signed message in examples for browser wallets

packages/wallet-connect/src/lib/wallet-connect.ts
This PR adds support for `signMessage` to WalletConnect
The functionality can be tested against this PR on the WalletConnect examples:
https://github.com/WalletConnect/web-examples/pull/310
Wallet Example:
https://react-wallet.walletconnect.com/walletconnect
Pull changes from wallet-selector:
```bash
git pull
```
Switch to this PR's branch
```bash
git switch add-sign-message-to-walletconnect
git checkout add-sign-message-to-walletconnect
yarn && yarn build:all && yarn nx serve react
```
=> feat: Add support for signMessage in WalletConnect

packages/my-near-wallet/src/lib/my-near-wallet.ts
This PR stops/disables the ability to trigger `signMessage` for NEAR Wallet since it's not supported.
This will avoid redirecting to a 404 page in the cases when users sign-in with NEAR Wallet and try the `signMessage`, since `near-wallet` in our side just wraps around the `my-near-wallet` setup it was enabled by default.
Closes: #973
=> fix: Disable signMessage for near-wallet

packages/account-export/src/lib/index.tsx, packages/modal-ui/src/lib/modal.tsx, scripts/update-package-json.js
=> fix: Fix Already passed to createRoot() warning

package.json, packages/meteor-wallet/src/lib/meteor-wallet.ts, yarn.lock
This fixes two bugs that have been popping up in Meteor Wallet:
* Signing out and signing back in a with a different wallet got stuck in a strange state with the old wallet still being used
* Errors were thrown for not being able to match the public key to the current transaction in places where they shouldn't have been
The update of the SDK here should resolve these issues.
=> Meteor Wallet: Update and bug fix

examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts, packages/modal-ui-js/src/lib/render-modal.ts, packages/modal-ui/src/lib/components/DerivationPath.tsx, packages/modal-ui/src/lib/components/Modal.tsx, packages/wallet-connect/README.md, packages/wallet-connect/src/lib/wallet-connect.ts
Closes: #1060 
- Made `methods` and `events` configurable from `setupWalletconnect`.
- Overrided default WC `methods` in angular example.
- Updated docs
- Improved error messages on `modal-ui` and `modal-ui-js`
=> fix: Make methods and events configurable on setupWalletConnect options.

packages/sender/src/lib/sender.ts
=> fix: Fix signIn for Sender while signed-in with another wallet

package.json, packages/core/docs/api/wallet.md, packages/core/src/lib/wallet/wallet.types.ts, packages/here-wallet/src/lib/index.ts, packages/here-wallet/src/lib/selector.ts, packages/modal-ui-js/src/lib/modal.ts, packages/modal-ui/src/lib/modal.tsx, yarn.lock
It was necessary to add the ability to associate an application inside an iframe with a parent window and allow seamless initialization and method calls. This will help integrate applications inside wallets. For example Telegram HERE Wallet:
https://github.com/near/wallet-selector/assets/14349805/0e9bbc9f-5222-40bf-9592-3689e151d317
`topLevelInjected` method is needed because wallet-selector is designed in such a way that only modal-ui knows about the contract that the application uses.
=> feat: Update HERE Wallet  and add topLevelInjected

package.json, packages/core/docs/api/wallet.md, packages/core/src/lib/wallet/wallet.types.ts, packages/here-wallet/src/lib/index.ts, packages/here-wallet/src/lib/selector.ts, packages/modal-ui-js/src/lib/modal.ts, packages/modal-ui/src/lib/modal.tsx, yarn.lock
Reverts near/wallet-selector#1091
This is the original PR:  https://github.com/near/wallet-selector/pull/1077
It was reverted at the direction of Pagoda leadership pending an internal review. We needed to release another change first. The feature is now approved and this revert will release the changes for the feature.
=> feat: Update HERE Wallet and add topLevelInjected

package.json, packages/account-export/package.json, packages/bitget-wallet/package.json, packages/coin98-wallet/package.json, packages/core/package.json, packages/here-wallet/package.json, packages/ledger/package.json, packages/math-wallet/package.json, packages/meteor-wallet/package.json, packages/mintbase-wallet/package.json, packages/modal-ui-js/package.json, packages/modal-ui/package.json, packages/my-near-wallet/package.json, packages/narwallets/package.json, packages/near-mobile-wallet/package.json, packages/near-snap/package.json, packages/nearfi/package.json, packages/neth/package.json, packages/nightly/package.json, packages/ramper-wallet/package.json, packages/sender/package.json, packages/wallet-connect/package.json, packages/wallet-utils/package.json, packages/welldone-wallet/package.json, packages/xdefi/package.json
=> chore: chore-bump-version-v8.9.7

packages/wallet-connect/src/lib/wallet-connect-client.ts
Fix commonjs build error when using wallet-connect package:
```
var modal = require('@walletconnect/modal');
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/pa/aurora-is-near/rainbow-bridge-next/node_modules/@near-wallet-selector/wallet-connect/node_modules/@walletconnect/modal/dist/index.js from /Users/pa/aurora-is-near/rainbow-bridge-next/node_modules/@near-wallet-selector/wallet-connect/index.cjs not supported.
Instead change the require of index.js in /Users/pa/aurora-is-near/rainbow-bridge-next/node_modules/@near-wallet-selector/wallet-connect/index.cjs to a dynamic import() which is available in all CommonJS modules.
```
=> fix: WalletConnect commonjs support.

packages/nightly/src/lib/nightly.ts
When the user has a dozen extensions, Nightly has stopped detecting correctly. Nightly is injected a few milliseconds later.
Increasing the time to check whether an extension is installed solves this problem.
=> fix: Increase timeout when checking installed Nightly extension.

packages/near-mobile-wallet/src/lib/init.wallet.ts, packages/near-snap/src/lib/selector.ts, packages/ramper-wallet/src/lib/ramper-wallet.ts
=> fix near-mobile-wallet, near-snap and ramper-wallet methods

.gitignore, .npmrc, package.json, packages/mintbase-wallet/package.json, yarn.lock
=> chore: [fix] - allow using npm or yarn

packages/ethereum-wallets/src/lib/index.ts
Hide the Ethereum wallets modal after a transaction error within a batch. Currently it lets the user sign the next transaction in the batch even though the App handles the rejected signAndSendTransactions() promise.
=> fix: Hide Ethereum wallets modal after tx error within a batch.

packages/core/src/lib/options.spec.ts, packages/core/src/lib/options.ts, packages/core/src/lib/services/provider/provider.service.spec.ts, packages/core/src/lib/services/provider/provider.service.ts, packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts, packages/core/src/lib/wallet-selector.spec.ts, packages/core/src/lib/wallet-selector.ts, packages/core/src/lib/wallet-selector.types.ts, packages/neth/src/lib/neth-lib.ts
=> feat: add failoverRPCprovider

package.json, packages/here-wallet/src/index.ts, packages/here-wallet/src/lib/index.ts, packages/here-wallet/src/lib/selector.ts, packages/here-wallet/src/lib/types.ts, packages/modal-ui/src/lib/components/WalletOptions.tsx, yarn.lock
@here-wallet/core updated to latest version
P.S. HERE/HOT Wallet does not support testnet
@race-of-sloths
=> feat: update @here-wallet/core

packages/my-near-wallet/src/lib/my-near-wallet.ts
=> fix: [fix] - Use BigInt for nonce calculation in transactions

packages/wallet-connect/src/lib/wallet-connect.ts
After the update of wallet selector to use NAJ `v4.0.x` the wallet-connect `signAndSendTransaction(s)` has stopped working because the type of the value of  `tx.encode()` has changed from `Buffer` to `Uint8Array` since NAJ v3  the `borsh@1.0.0` update.
WalletConnect uses [formats and encodes](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L1454) the payload and this handles the `Buffer` and `Uint8Array` differently.
This PR adds support to handle the result returned from a wallet that uses latest version of NAJ (Uint8Array) and still keeps support for the old versions (Buffer).
I have also updated the web-examples of WalletConnect to add support for the latest version(s) of NAJ: …
=> fix: Handle transactions after NAJ update to v4.0.x for WalletConnect

packages/ethereum-wallets/src/lib/index.ts, packages/ethereum-wallets/src/lib/modal.ts
Bug fixes:
- Ethereum transaction details button state (don't close the details when signing the transaction)
- During account or network switch, if skipSignInAccessKey is active then disconnecting is not necessary.
=> Ethereum tx show details - skipSignInAccessKey bugfix

package.json, yarn.lock
- Upgrade @peersyst/near-mobile-wallet to v1.1.1, enhancing error handling when users close the QR scan modal.
=> feat: Bump @peersyst/near-mobile-wallet package to 1.1.1 version

tsconfig.base.json
=> fix: Remove @near-js/ aliases from tsconfig.base.json

packages/core/package.json, packages/core/src/lib/wallet-selector.spec.ts
- Remove un-necessary peerDependency from core package
- Remove individual imports of `@near-js/` packages , mixing the `@near-js/*`  and `near-api-js` can lead to mismatch of versions keep imports to  `near-api-js` for consistency.
=> fix: Fix imports and remove unnecessary peer dependency

package.json, yarn.lock
- Upgraded `@peersyst/near-mobile-wallet to v1.1.2`, fixing an issue where signMessage did not correctly verify the signature when a `callbackUrl` was provided.
=> fix: Bump @peersyst/near-mobile-wallet package to 1.1.2 version

packages/core/src/lib/locale/zh-tw.json
=> docs: add zh-tw translation

packages/nightly/src/lib/nightly.ts
=> fix: Removal of the isMobile check in Nightly

package.json, yarn.lock
Upgraded @peersyst/near-mobile-wallet to v1.1.4, fixing polling behavior when the browser remains in the background on mobile.
=> fix: bump @peersyst/near-mobile-signer to v1.1.4

packages/react-hook/src/lib/WalletSelectorProvider.tsx
Our current `signAndSendTransactions` hook returns a vector of `FinalExecutionOutcome`, but people is generally waiting for the actual result
This PR modifies the hook so it returns the result of the Transaction, and not the execution object itself
=> fix: signandsendtxs hook returns results

packages/ethereum-wallets/src/lib/index.ts
This pr introduces a fix for MetaMask wallet. It fixes the onboarding of new users
Metamask has a [check](https://github.com/MetaMask/core/blob/v360.0.0/packages/transaction-controller/src/utils/validation.ts#L100-L110) that prevents the execution of 'external' transactions (i.e., those originating outside MetaMask), when these transactions have an 'internal' account address in the to field (i.e., a user's own address within MetaMask) and contain non-empty data. When issuing an onboarding transaction, we set the to field to the user's own address and utilize the data field to pass required parameters to the Wallet Contract, specifically to add the provided public key to the account.
We set hash to value for AddKey/DeleteKey to bypass that metamask check. In the Wallet Contract itself …
=> fix: metamask onboarding

package.json
Based on the issue reported in https://github.com/near/wallet-selector/issues/1346,  where `signerId is undefined` when using Meteor Wallet to create a function call key, I've pinned `near-api-js` to version 5.0.0 to resolve the incompatibility.
This version has been tested and works correctly .
This image shows a test performed on a HOT wallet
=> Force use of near-api-js@5.0.0 to fix signerId is undefined

examples/react/components/Content.tsx, examples/react/components/Form.tsx, packages/arepa-wallet/src/lib/arepa-wallet.ts, packages/bitget-wallet/src/lib/bitget-wallet.ts, packages/coin98-wallet/src/lib/coin98-wallet.ts, packages/core/docs/api/wallet.md, packages/core/docs/guides/custom-wallets.md, packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts, packages/core/src/lib/wallet/wallet.types.ts, packages/ethereum-wallets/src/lib/index.ts, packages/here-wallet/src/lib/selector.ts, packages/hot-wallet/src/lib/index.ts, packages/intear-wallet/src/lib/intear-wallet.ts, packages/ledger/src/lib/ledger.ts, packages/math-wallet/src/lib/math-wallet.ts, packages/meteor-wallet-app/src/lib/meteor-wallet-app.ts, packages/meteor-wallet/src/lib/meteor-wallet.ts, packages/my-near-wallet/src/lib/my-near-wallet.ts, packages/narwallets/src/lib/narwallets.ts, packages/near-mobile-wallet/src/lib/init.wallet.ts, packages/near-snap/src/lib/selector.ts, packages/nightly/src/lib/nightly.ts, packages/okx-wallet/src/lib/okx-wallet.ts, packages/ramper-wallet/src/lib/ramper-wallet.ts, packages/react-hook/README.md, packages/react-hook/src/lib/WalletSelectorProvider.tsx, packages/sender/src/lib/sender.ts, packages/wallet-connect/src/lib/wallet-connect.ts, packages/welldone-wallet/src/lib/welldone.ts, packages/xdefi/src/lib/xdefi.ts
This pull request introduces the new `createSignedTransaction` and `signTransaction` methods to the wallet-selector. This method enables wallets to create signed transactions and return a Signed Transaction object, empowering developers to handle raw signed transactions for custom workflows.
- Added the `createSignedTransaction(receiverId, actions)` method and `signTransaction(transaction)` method to the wallet type and behavior interface.
- Added mandatory `signTransaction` as a mandatory method for each wallet
- Implemented or stubbed `createSignedTransaction` in all wallet modules. For unsupported wallets, the method includes logging parameters and throwing "not supported" errors.
- Extended wallet type definitions and documentation to include signing transaction.
- React example app …
=> feat: Implement createSignedTransaction and returns SignedTransaction

packages/core/src/lib/services/storage/web-storage.service.ts, packages/core/src/lib/wallet-selector.ts, packages/react-hook/src/lib/WalletSelectorProvider.tsx
Some users have complained that wallet selector is not initialized when loaded, and that there is no way to know when it actually finished being initialized
I have make the `setupWalletSelector` wait for initialization, but it is important to know that this is not an amazing solution, as "logged in" instances still need to wait for all "not logged in" wallets to initialize
A new PR - which I do not have time to make right now - should deal with "early return" or "cached init", meaning that `wallet-selector` should do something smart to check all wallets if it knows that a single wallet is already logged in
=> fix: always initialize wallet selector

.changeset/beige-kids-push.md, packages/core/src/lib/wallet-selector.spec.ts, packages/core/src/lib/wallet-selector.ts
Remove unnecessary await from `getNetworkPreset` function in wallet selector
=> chore: remove unnecessary await from getNetworkPreset in wallet selector

examples/react/package.json, examples/vanilla/package.json
Example were being included in changeset version tracking, which is not desired since they are development/demonstration packages that shouldn't be published or versioned separately
This PR excludes the example packages from changeset tracking by marking them as `private: true` in their respective `package.json` files.
According to [changeset documentation](https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#ignore-array-of-packages), private packages are automatically ignored by changesets by default.
**Failed Action:** https://github.com/near/wallet-selector/actions/runs/17257342584/job/48971797602
```
🦋  error an error occurred while publishing @near-wallet-selector-examples/react: ERR_PNPM_PACKAGE_VERSION_NOT_FOUND undefined 
🦋  error {
🦋  error   "error": { …
```
=> fix: exclude example packages from changeset tracking

.changeset/tiny-sheep-camp.md, examples/react/components/Content.tsx, examples/react/components/Form.tsx, packages/meteor-wallet-app/src/lib/meteor-wallet-app.ts, packages/react-hook/src/lib/WalletSelectorProvider.tsx
Added `createSignedTransaction`, `signTransaction`, `getPublicKey`, `signNep413Message`, `signDelegateAction` to meteor wallet app to keep up with selector changes.
As part of adding these methods, this PR also added 
1. Missing methods into the `near-wallet-selector/react-hook` package.
2. Few more buttons and checkboxes to test these methods in the example 
Although not shown in the video, we have tried broadcasting the signed transaction, signed delegate action in the example, and all of them work as expected. `signNep413Message` is verified through a helper method within the example too.
https://github.com/user-attachments/assets/6d837e33-25fd-4845-b80c-233cf4a6cde6
=> Update Meteor Wallet App
