near/wallet-selector

- src/modal/ModalHelper.tsx
- src/modal/component/Modal/Modal.styles.ts
- src/modal/component/Modal/Modal.tsx
- src/wallets/injected/SenderWallet.ts
Added a check if the Sender Wallet extension is not installed we provide the user with a UI and directions to download it.
> Added SenderWallet install message

- README.md
- Restructured README.
- Added reference to example integration.
> #53 Restructured README

- e2e/example.e2e.ts
- package-lock.json
- package.json
- playwright.config.ts
- Added `@playwright/test` to enable Playwright within the project.
- Added `playwright` to avoid inefficiently having to run `npx playwright`.
- Added `test:e2e` NPM script to run Playwright tests.
- Added an example test to prove the setup is working correctly.
- Playwright has been configured to find `*.e2e.ts` files within the `e2e` directory.
> #78 Setup Playwright

- src/controllers/WalletController.ts
- src/interfaces/IWallet.ts
- src/modal/Modal.tsx
- src/types/CustomWalletOptions.ts
- src/wallets/BaseWallet.ts
- src/wallets/CustomWallet.ts
- src/wallets/browser/NearWallet.ts
- src/wallets/hardware/LedgerWallet.ts
- src/wallets/injected/SenderWallet.ts
- src/wallets/types/BrowserWallet.ts
- src/wallets/types/HardwareWallet.ts
- src/wallets/types/InjectedWallet.ts
- Added `getInfo` method to each wallet implementation.
- Updated example integration to use new functionality.
- Fixed a few async issues to handle Promise rejections.
> #118 Simplify Wallet Info Logic

- .eslintrc.js
- src/modal/Modal.tsx
- src/services/logging.service.spec.ts
- src/services/logging.service.ts
- src/utils/types.ts
- src/wallets/browser/NearWallet.ts
- src/wallets/hardware/LedgerWallet.ts
- src/wallets/injected/SenderWallet.ts
> Creating logging service

- example/package.json
closes #146
This needs to be merged ASAP
> Fixing prepare script issues

- examples/react/src/components/Content.tsx
- Added back `preventDefault` call on submit of a message.
> Fix React Example

- README.md
- Rewritten the API Reference section to be more detailed and better structured.
- README preview [here](https://github.com/near-projects/wallet-selector/blob/api-reference-improvements/README.md#api-reference).
> API Reference Improvements

- examples/angular/src/app/components/content/content.component.ts
- examples/react/src/components/Content.tsx
- examples/vue/src/components/Content.vue
- src/core/Contract.ts
- src/interfaces/InjectedSenderWallet.ts
- src/wallets/Wallet.ts
- src/wallets/hardware/LedgerWallet.ts
- src/wallets/injected/SenderWallet.ts
- Improved typing support for `.contract.view(params)`.
- Aligned responses of each wallet for `.contract.signAndSendTransaction(params)`.
- Updated examples to reflect changes.
> View & Change Method Improvements

- src/config.spec.ts
- Tests for the `getConfig` function which is located in `/src/config.js`
- Tests check if getConfig function returns the correct config for a given networkId `"mainnet" | "testnet" | "betanet"`
> Config file tests

- README.md
- Added a "Known Issues" section to the README to make users aware of an issue with Sender Wallet.
> Document Known Issues

- CONTRIBUTING.md
- decorate-angular-cli.js
- yarn.lock
- Fixed `yarn.lock` changes.
- Fixed Angular script.
- Fixed commands in contributing file.
> chore: Minor fixes from #196

- src/wallets/browser/NearWallet.spec.ts
Adding unit tests for NearWallet.ts file.
> test: Added createNearWallet setup and isAvailable test

- packages/near-wallet-selector/README.md
- packages/near-wallet-selector/src/controllers/WalletController.ts
- packages/near-wallet-selector/src/index.ts
- packages/near-wallet-selector/src/interfaces/Options.ts
Added support for passing a `WalletModule` factory function to the `wallets` configuration.
> feat: [SQAC-102] Support for Wallet Modules

- packages/ledger-wallet/README.md
- packages/math-wallet/README.md
- packages/near-wallet/README.md
- packages/sender-wallet/README.md
- packages/wallet-connect/README.md
- Updated readme for `NEAR Wallet`, `Sender Wallet`, `Ledger Wallet` and` Math Wallet`
Closes # (issue) No issue opened for this PR.
> docs: Updated docs for wallets

- packages/math-wallet/src/lib/math-wallet.ts
Inside the math-wallet.ts file the signAndSendTransactions was not implemented. I implemented the logic to handle multiple transactions using the Math Wallet extension.
> feat: Finished signAndSendTransactions method

- packages/ledger/src/lib/ledger.ts
- Implemented `signAndSendTransactions` method to support batch transactions for Ledger.
> feat: [SQAC-104] Add Batch Transaction Support for Ledger

- packages/ledger/src/lib/ledger.ts
- Fixed bug the for signOut in Ledger wallet.
> fix: [SQAC-117] Bug fix for 'signOut' method in Ledger

- package.json
- packages/core/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/near-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
Updated package versions to `3.0.1`
> chore: Bump Version to 3.0.1

- packages/core/src/lib/WalletController.ts
- packages/core/src/lib/modal/Modal.tsx
- packages/core/src/lib/wallet/wallet.ts
- packages/ledger/src/lib/ledger.spec.ts
- packages/ledger/src/lib/ledger.ts
Removed the need for users to input their account id when connecting with the Ledger Wallet. It now automatically fetches the account id connected with your public key you are connecting with and validates it. If there is no account id connected with public key you are trying to connect with it will show you an error message.
> feat: Removed account id requirement for ledger connecting

- packages/core/src/lib/modal/components/LedgerDerivationPath.tsx
- packages/core/src/lib/modal/components/Modal.tsx
- packages/core/src/lib/modal/components/WalletNetworkChanged.tsx
- packages/core/src/lib/modal/components/WalletNotInstalled.tsx
- packages/core/src/lib/modal/components/WalletOptions.tsx
Split up modal logic into separate components for encapsulate and simplify state and logic.
> refactor: Sqac 111 improve routing logic within modal

- packages/core/src/lib/modal/components/Modal.tsx
- packages/sender/src/lib/injected-sender.ts
- packages/sender/src/lib/sender.ts
- Fixed bug when disconnecting with Sender
> fix: Fixed Sender Discconect bug

- packages/core/src/lib/modal/components/Modal.tsx
- Close modal by pressing ESC key.
> chore: Close Modal by Pressing the ESC Key

- packages/core/src/lib/modal/components/WalletOptions.tsx
- packages/core/src/lib/wallet/wallet.ts
- packages/ledger/src/lib/ledger.spec.ts
- packages/ledger/src/lib/ledger.ts
- packages/math-wallet/src/lib/math-wallet.ts
- packages/near-wallet/src/lib/near-wallet.spec.ts
- packages/near-wallet/src/lib/near-wallet.ts
- packages/sender/src/lib/sender.ts
- packages/wallet-connect/src/lib/wallet-connect.ts
Modified `isAvailable` function to return a Promise.
> refactor: Modified isAvailable function to be async

- packages/core/src/lib/modal/components/LedgerDerivationPath.tsx
- Connect to ledger by pressing enter key when derivation path input is focused.
> chore: Connect To Ledger by Pressinng Enter

- docs/guides/custom-wallets.md
Added a guide for creating custom wallets.
> docs: Create Guide for Custom Wallets

- packages/core/src/lib/store.ts
- Switched store implementation to use multiple RxJS streams to remove the hack in `dispatch`.
> refactor: Correct Store Implementation

- packages/sender/src/lib/injected-sender.ts
- packages/sender/src/lib/sender.ts
> fix: Changed response interface for rpcChanged

- examples/angular/src/styles.scss
- examples/react/src/styles.scss
- packages/modal-ui/README.md
- packages/modal-ui/project.json
- packages/modal-ui/src/lib/components/Modal.tsx
- packages/modal-ui/src/lib/components/styles.css
- Exposed styles.css.
- Prefixed  css class `.modal-wrapper` to `.nws-modal-wrapper`
- Import in dApp via:  `@import "~@near-wallet-selector/modal-ui/styles.css";`
> feat: Migrate Styling to CSS

- package.json
- packages/core/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- Updated package versions to `4.0.0`.
- Updated package description and keywords.
- Realigned `dev` with `main`.
> chore: Bump Version to 4.0.0

- packages/core/src/lib/testUtils.ts
- packages/ledger/src/lib/ledger.spec.ts
> test: Sqac 150 ledger wallet unit testing

- packages/modal-ui/README.md
- packages/modal-ui/src/lib/components/WalletOptions.tsx
- packages/modal-ui/src/lib/components/styles.css
- Throw error when a deprecated wallet is selected.
> chore: Handle Deprecated Wallets in UI

- package.json
- packages/core/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/modal-ui/package.json
- packages/modal-ui/src/lib/components/styles.css
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- Fixed issue with the new Sender icon in dark mode.
- Bumped version to `4.1.1`.
> 4.1.1 Release Fixes

- examples/angular/src/app/components/content/content.component.ts
FIxes issue where UI doesn't update after connecting with wallet.
> fix: Updating this.account variable after updating accounts list

- packages/nightly-connect/project.json
- packages/nightly-connect/tsconfig.lib.json
- packages/wallet-connect/project.json
- packages/wallet-connect/tsconfig.lib.json
- Changed bundler for `@near-wallet-selector/wallet-connect` and `@near-wallet-selector/nightly-connect`to support (esm, cjs, umd) to align with other packages.
> build: Support (esm, cjs, umd) for WalletConnect Package

- packages/ledger/src/lib/ledger.ts
Ledger will now show in UI if not available. When clicked an error will show up.
> fix: Ledger will now show in UI if not available

- package.json
- packages/core/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- packages/near-wallet/package.json
- packages/near-wallet/src/lib/near-wallet.ts
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- Fixed `walletUrl` for **mainnet** for `MyNearWallet`.
- Switched `deprecated` flag to `false` for NEAR Wallet.
Closes #350
> 5.0.2 Release Hotfixes

- packages/modal-ui/src/lib/components/styles.css
This PR fixes alignment issues for icon images in the connecting flow where css is being overridden in some dApps.
Closes #374
> style: Fix Icon Alignment Issue

- CONTRIBUTING.md
> Add wallet selector contributing requirements

- CONTRIBUTING.md
This PR is to describe branching and releasing in the CONTRIBUTING.md file.
Addresses point 3 in this issue #375 
> docs: Added Branching and Release Process sections in CONTRIBUTING.md

- packages/core/README.md
- Added `indexerUrl` to the docs for custom `Network` in  `core` package.
> docs: Update Docs for `core` Package

- packages/ledger/README.md
- Added known issue when bundling `@near-wallet-selector/ledger` with parcel.
Closes issue #411
> docs: Add Ledger Known Issue when Bundling with Parcel

- CONTRIBUTING.md
- Updated third-party contributing guidelines.
Closes #402
> docs: Update Third Party Contributing Guideline

- package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
> chore: Bump Version to 6.0.1

- packages/modal-ui/src/lib/components/Modal.tsx
> Test commit

- package.json
- yarn.lock
Minor version update. One inner dependency was updated to fix problem happening on Vercel.
> fix: update Nightly Connect library version

- .gitignore
- .vscode/settings.json
- package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui-js/src/lib/components/WalletAccount.ts
- packages/modal-ui-js/src/lib/components/WalletConnectionFailed.ts
- packages/modal-ui-js/src/lib/components/WhatIsAWallet.ts
- packages/modal-ui-js/src/lib/render-modal.ts
- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/package.json
- packages/modal-ui/src/lib/components/AlertMessage.tsx
- packages/modal-ui/src/lib/components/ConnectionResult.tsx
- packages/modal-ui/src/lib/components/WalletHome.tsx
- packages/modal-ui/src/lib/components/styles.css
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
> fix: Modal responsive fixes

- package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui-js/src/lib/components/GetAWallet.ts
- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/package.json
- packages/modal-ui/src/lib/components/WalletHome.tsx
- packages/modal-ui/src/lib/components/styles.css
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
> fix: Get a wallet list, removed bridge and hardware

- packages/wallet-connect/package.json
This PR fixes issue:  https://github.com/near/wallet-selector/issues/454
> fix: Added "near-api-js" peerDependency to the "wallet-connect"

- examples/angular/src/app/components/content/content.component.ts
- examples/react/components/Content.tsx
- packages/wallet-connect/src/lib/wallet-connect.ts
- Fixes wrong method call on `signAndSendTransactions`
> fix: Fix signAndSendTransactiosns for wallet-connect

- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/src/lib/components/styles.css
> fix the modal close button padding

- packages/modal-ui-js/docs/api/modal.md
Fixes https://github.com/near/wallet-selector/issues/473
> docs: Added docs for modal-ui-js

- packages/modal-ui-js/src/lib/components/SpecifyDerivationPath.ts
- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/src/lib/components/DerivationPath.tsx
- packages/modal-ui/src/lib/components/styles.css
- Added what's a wallet link in modal UI.
> fix: Add `What's this?` link to Ledger

- packages/core/docs/api/wallet.md
- packages/modal-ui-js/src/lib/render-modal.ts
- packages/wallet-connect/src/lib/wallet-connect.ts
`verifyOwner` function is now a supported function in WalletConnect wallet.
> feat: Added verifyOwner function to wallet-connect

- CONTRIBUTING.md
- package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
> chore: Bump version to 7.1.0

- packages/modal-ui/src/lib/components/Modal.tsx
- packages/modal-ui/src/lib/components/ScanQRCode.tsx
- packages/nightly-connect/src/lib/nightly-connect.ts
> feat: Nightly Connect - QR Modal implementation

- CONTRIBUTING.md
> Update default wallet list criteria

- examples/angular/src/app/app.component.ts
- packages/core/docs/api/wallet.md
- packages/core/src/lib/wallet/wallet.types.ts
- packages/here-wallet/src/lib/here-wallet.ts
- packages/modal-ui-js/src/lib/render-modal.ts
- packages/modal-ui/src/lib/components/Modal.tsx
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- packages/near-wallet/src/lib/near-wallet.ts
Fixes https://github.com/near/wallet-selector/issues/517.
> fix: added successUrl and failureUrl

- package.json
- packages/core/README.md
- packages/core/docs/api/selector.md
- packages/core/src/lib/constants.ts
- packages/core/src/lib/options.ts
- packages/core/src/lib/options.types.ts
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- packages/core/src/lib/store.ts
- packages/core/src/lib/store.types.ts
- packages/core/src/lib/wallet-selector.types.ts
- packages/modal-ui-js/src/lib/modal.ts
- packages/modal-ui-js/src/lib/render-modal.ts
- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/src/lib/components/WalletOptions.tsx
- packages/modal-ui/src/lib/components/styles.css
- Added `optimizeWalletOrder` option when setting up wallet-selector. 
- By default it is `true`.
- It will prioritize last signed in wallets, then installed wallets over not installed and deprecated wallets.
> feat: Added wallet order optimization

- examples/react/components/Content.tsx
- examples/react/contexts/WalletSelectorContext.tsx
- packages/neth/src/lib/neth-lib.ts
- Fixed `keystore` bug for Neth.
- Fixed types for react example.
> fix: Bug fixes for Neth and React Example

- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/src/lib/components/styles.css
- packages/welldone-wallet/src/lib/welldone.ts
- Fixed wallet options title on mobile devices. 
- Renamed WELLDONE to Welldone. 
- Centered elements in connecting view for mobile devices.
> UI fixes for mobile view

- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/src/lib/components/styles.css
- packages/welldone-wallet/src/lib/welldone.ts
- Fixed wallet options title on mobile devices.
- Renamed WELLDONE to Welldone.
- Centered elements in connecting view for mobile devices.
> style: UI fixes for mobile view

- packages/my-near-wallet/README.md
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- Set the `deprecated` flag to `true` for MyNearWallet by default.
> chore: Deprecate MyNearWallet

- examples/react/components/Content.tsx
- package.json
- packages/core/src/lib/wallet/wallet.types.ts
- packages/here-wallet/src/lib/utils.ts
- packages/math-wallet/src/lib/injected-math-wallet.ts
- packages/modal-ui-js/src/lib/modal.types.ts
- packages/modal-ui/src/lib/components/DerivationPath.tsx
- packages/modal-ui/src/lib/components/Modal.types.ts
- packages/nearfi/src/lib/injected-nearfi.ts
- packages/nightly-connect/src/lib/nightly-connect.ts
- packages/nightly/src/lib/injected-nightly.ts
- packages/sender/src/lib/injected-sender.ts
- tsprune.json
- yarn.lock
> chore: SQC-388/unused code detection

- packages/my-near-wallet/README.md
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- Reverted MyNearWallet deprecation, it will be postponed for a later date.
> chore: Revert  MyNearWallet deprecate flag

- packages/core/src/lib/wallet/wallet.types.ts
This PR extends the `InjectedWalletBehaviour` and `BrowserWalletBehaviour` types to include new, optional, mutually exclusive methods:
- `buildImportAccountsUrl()` (browser wallets) returns the URL for the import accounts page on the wallet. The encrypted JSON string will be appended onto it as a fragment.
- `importAccountsInSecureContext({ accounts: Array<{ accountId: string, publicKey: string }> })` takes an array of accounts to import, represented by objects with an `accountId` and `privateKey`. It returns a `Promise<void>` though there could be some value in utilizing return codes for injected wallets. For now it's not worth taking on the added complexity and instead we can rely on thrown exceptions to indicate failure.
I've opted to have these methods take a set of accounts rather …
> feat: add new methods to WalletBehaviour types

- README.md
- packages/core/docs/api/selector.md
- packages/core/docs/api/state.md
- packages/core/docs/guides/custom-wallets.md
- packages/core/docs/guides/multilanguage-support.md
- This PR is to add missing docs and improve some of them.
> docs: Update and improve docs

- packages/wallet-connect/src/lib/wallet-connect.ts
Added logic for `signMessage` method in wallet-connect package.
> Added signMessage logic to wallet-connect

- package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui-js/src/lib/styles.css
- packages/modal-ui/package.json
- packages/modal-ui/src/lib/components/styles.css
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
> chore: Version bump to 7.4.0

- packages/core/src/lib/locale/ar.json
- packages/core/src/lib/translate/translate.ts
> Add Arabic translation

- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
> chore: SQC-432/Add aditional metadata to packages

- package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
> chore: Bumped version to 7.5.0

- packages/coin98-wallet/project.json
- packages/modal-ui-js/project.json
- packages/wallet-utils/project.json
> chore: SQC431/Add `deploy` script to all packages

- packages/narwallets/package.json
- Added more metadata in the `package.json` of  **Narwallets** to align with other packages.
> chore: Add additional metadata in `package.json` of Narwallets

- packages/account-export/src/lib/components/ExportAccount.tsx
- packages/core/src/lib/wallet/wallet.types.ts
- packages/meteor-wallet/src/lib/meteor-wallet.ts
This PR adds the account import URL for Meteor wallet and the logic required to allow injected wallets to use URLs when appropriate.
> feat: implement URL export for injected wallets

- packages/account-export/INTEGRATION.md
- packages/account-export/README.md
Add documentation on how a Wallet Selector wallet integration can implement account import. This should be merged once the encryption method is brought over so that these docs can reference it.
> docs: documentation on implementation

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bumped version to 7.6.0

- packages/coin98-wallet/src/lib/coin98-wallet.ts
- packages/math-wallet/src/lib/math-wallet.ts
- packages/nearfi/src/lib/nearfi.ts
- packages/neth/src/lib/neth.ts
Speed up wallet-selector. Delete unnecessary timeouts and remove waitFor function where it don't needed.
> perf: Addressing timeouts

- packages/coin98-wallet/src/lib/coin98-wallet.ts
- packages/core/docs/api/wallet.md
- packages/core/src/lib/wallet/wallet.types.ts
- packages/here-wallet/src/lib/selector.ts
- packages/ledger/src/lib/ledger.spec.ts
- packages/ledger/src/lib/ledger.ts
- packages/math-wallet/src/lib/math-wallet.ts
- packages/meteor-wallet/src/lib/meteor-wallet.ts
- packages/my-near-wallet/src/lib/my-near-wallet.spec.ts
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- packages/nearfi/src/lib/nearfi.ts
- packages/neth/src/lib/neth-lib.ts
- packages/neth/src/lib/neth.ts
- packages/nightly-connect/src/lib/nightly-connect.ts
- packages/nightly/src/lib/nightly.ts
- packages/opto-wallet/src/lib/opto-wallet.spec.ts
- packages/opto-wallet/src/lib/opto-wallet.ts
- packages/sender/src/lib/sender.ts
- packages/wallet-connect/src/lib/wallet-connect.ts
- packages/welldone-wallet/src/lib/welldone.ts
- packages/xdefi/src/lib/xdefi.ts
Added `publicKey?: string` to `Account` type.
> feat: Added publicKey to Account type

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version for all packages to `v7.6.1`
> chore: Bumped version to 7.6.1

- packages/account-export/src/lib/components/AccountSelect.tsx
- packages/account-export/src/lib/components/ExportAccount.tsx
- packages/account-export/src/lib/styles.css
- packages/core/src/lib/locale/en.json
This PR contains minor cosmetic improvements on `account-export` package:
> style: UI/UX improvements and cosmatic changes on account-export

- packages/account-export/src/lib/components/AccountSelect.tsx
- packages/account-export/src/lib/components/Complete.tsx
- packages/account-export/src/lib/components/ExportAccount.tsx
- packages/account-export/src/lib/styles.css
- packages/core/src/lib/locale/en.json
This PR contains following changes:
1. Bug fix on passing selected accounts only to importAccountsInSecureContext interface
2. Improvements on Styles/UI on account-export flow
- Truncate long account name
- Tooltip
- Improve Complete Page layout
> style: Minor bug fix and cosmetic improvements on account-export package

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Bumped version for all packages to v7.6.2
> chore: Bumped version to 7.6.2

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Reverts near/wallet-selector#683
> Revert "chore: Bumped version to 7.6.2"

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.7.0` for all packages.
- Added additional metadata for `account-export` package to align with the other packages."
> chore: Bumped version to 7.7.0

- packages/my-near-wallet/src/lib/my-near-wallet.ts
> fix: Connection issue with wallets (PublicKey)

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.8.0` for all packages.
> chore: Bump version to 7.8.0

- examples/angular/src/app/components/content/content.component.ts
- examples/angular/src/app/interfaces/account-balance.ts
- examples/react/components/Content.tsx
- Added error handling when viewing the account in examples and show an error message when the account has no balance.
Closes (#692)
> fix: Add error handlig on examples when viewing the Account

- packages/meteor-wallet/src/lib/meteor-wallet.ts
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- packages/wallet-connect/src/lib/wallet-connect.ts
> fix: Repair return undefined for publicKey

- examples/react/components/Content.tsx
- Fixed bug when checking for balance in react example.
> fix: Add import statement for BN in react example

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `7.8.1` for all packages.
> chore: Bump version to 7.8.1

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.8.2` for all packages.
> chore: Bump version to 7.8.2

- package.json
- yarn.lock
* Fix serialise binary arguments for function calls.
* Fix multiple function calls
* Add new UI for HERE Connector (Iframe widget)
> here-wallet: upgrade to 1.4

- examples/angular/project.json
- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.9.0` for all packages.
- Increased the limit for the production bundle for the angular example.
> chore: Bump version to 7.9.0

- packages/modal-ui-js/src/lib/components/WalletNotInstalled.ts
> fix: WalletNotInstalled back button fix

- packages/wallet-connect/README.md
- Fixed broken links in the `wallet-connect` package.
> docs: Fix broken links in docs

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.9.1` for all packages.
> chore: Bump version to 7.9.1

- packages/sender/src/lib/injected-sender.ts
- packages/sender/src/lib/sender.spec.ts
- packages/sender/src/lib/sender.ts
- packages/sender/tsconfig.json
- Fixed issue with `json` files by adding `resolveJsonModule` in tsconfig.json.
- Mocked most of the `window.near`.
NOTE: This might need some extra work around mocks in `window.near`.
> Fix Sender tests

- packages/account-export/src/lib/components/AccountSelect.tsx
- packages/account-export/src/lib/styles.css
Minor UI improvements on account export modal
> style: Minor Account Export UI improvements

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.9.2` for all packages.
> chore: Bump version to 7.9.2

- packages/core/src/lib/locale/vi.json
Translated **exportAccounts** section and make some adjustments
> Translate new strings into Vietnamese

- README.md
- packages/wallet-connect/README.md
> improve docs to be more explicit

- packages/core/docs/guides/multilanguage-support.md
- packages/core/src/lib/translate/translate.ts
> docs: Added missing languages, sorted alphabetically

- README.md
- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/core/src/lib/locale/vi.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/README.md
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v7.9.3` for all packages.
- Aligned the branch with the `mian` branch too.
> chore: Bump version to 7.9.3

- examples/react/contexts/WalletSelectorContext.tsx
- examples/react/contexts/WalletSelectorExportContext.tsx
there are 2 issues detected by sonarlint 
- missing dependency of `modal` in `useEffect`
- not using `useMemo` for context provider value
and added a loading state
> refactor code to remove sonarlint warning

- packages/account-export/README.md
- packages/coin98-wallet/README.md
- packages/core/docs/api/selector.md
- packages/core/docs/guides/custom-wallets.md
- packages/core/docs/guides/multilanguage-support.md
- packages/finer-wallet/README.md
- packages/here-wallet/README.md
- packages/ledger/README.md
- packages/math-wallet/README.md
- packages/meteor-wallet/README.md
- packages/modal-ui-js/README.md
- packages/modal-ui/README.md
- packages/my-near-wallet/README.md
- packages/narwallets/README.md
- packages/near-snap/README.md
- packages/near-wallet/README.md
- packages/nearfi/README.md
- packages/nightly-connect/README.md
- packages/nightly/README.md
- packages/opto-wallet/README.md
- packages/sender/README.md
- packages/wallet-connect/README.md
- packages/wallet-utils/README.md
- packages/welldone-wallet/README.md
- packages/xdefi/README.md
> docs: Updated docs

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to v8.0.0

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> version bump to v8.0.1

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v8.0.2` for all packages.
> chore: Bump version to v8.0.2

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v8.0.3` for all packages.
> chore: Bump version to v8.0.3

- packages/core/src/lib/locale/ar.json
- packages/core/src/lib/locale/bg.json
- packages/core/src/lib/locale/en.json
- packages/core/src/lib/locale/es.json
- packages/core/src/lib/locale/hi.json
- packages/core/src/lib/locale/hr.json
- packages/core/src/lib/locale/ko.json
- packages/core/src/lib/locale/mk.json
- packages/core/src/lib/locale/sl.json
- packages/core/src/lib/locale/sr.json
- packages/core/src/lib/locale/vi.json
- packages/core/src/lib/locale/zh.json
- packages/modal-ui-js/src/lib/components/GetAWallet.ts
- packages/modal-ui/src/lib/components/WalletHome.tsx
- Added `walletTypes` key in translation files
- Used translations in `modal-ui` and `modal-ui-js`
- Refactored `Get Wallets` view.
> fix: Added walletTypes keys in translation files.

- packages/account-export/src/lib/styles.css
- Fixed text color for `Wallet name` and `Wallet type` in the wallet list when selected.
> style: Improve styles in account-export modal

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to v8.1.0 for all packages.
> chore: Bump version to v8.1.0

- packages/modal-ui-js/src/lib/components/GetAWallet.ts
- packages/modal-ui/src/lib/components/WalletHome.tsx
> chore: Filter out "instant link" wallet types

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.1.1

- packages/account-export/README.md
This PR contains read me of account export package with showing list of wallets that are supporting account export feature.
> docs: Update read me on account export to show list of supported wallets

- packages/account-export/src/lib/styles.css
Minor UX improvement on `account-export` package, on hover to show password
> style: Show password on hover

- package.json
- yarn.lock
> fix: Added changes for dependencies

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.1.3

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/nearfi/src/lib/nearfi.ts
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- yarn.lock
- NearFi not showing in Wallet Selector (#826)
> v8.1.3 Release (dev -> main)

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
bump version to 8.1.4
(https://github.com/near/wallet-selector/pull/831 need to be merged in first)
> chore: Bump version to 8.1.4

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.2.0

- .github/workflows/bump-version.yml
> fix: fix bump-version workflow

- package.json
- yarn.lock
> chore: Bump walletconnect/types from 2.7.8 to 2.8.6

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.2.1

- .github/workflows/bump-version.yml
> fix: Added build step in bump-version file

- packages/default-wallets/project.json
> fix: Delete deploy script from default-wallets

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/docs/api/wallet.md
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v8.3.0` for all packages.
> Bump version to v8.3.0

- .github/workflows/dev-pr.yml
- Added write access for `issues`, `pull-requests`, and `actions`  to the Dev PR workflow.
> Add permissions to Dev PR workflow.

- .github/workflows/dev-pr.yml
This PR is about aligning the changes made in the Dev PR workflow.
> Align dev with the main branch

- package.json
- yarn.lock
> chore: Revert "Bump @ledgerhq/hw-transport from 6.28.5 to 6.28.6"

- packages/finer-wallet/src/lib/finer.ts
> fix: set Finer wallet as depricated

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.4.0

- examples/angular/src/polyfills.ts
- package.json
- packages/near-snap/README.md
- tsconfig.base.json
- yarn.lock
> fix: Added dependencies and fixes to angular example

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: bump version to 8.5.0

- .github/workflows/bump-version.yml
- Added write access for issues, pull-requests, and actions to the bump-version workflow.
> ci: Add permissions to bump-version workflow

- .github/workflows/deploy-angular-example.yml
- examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts
> ci: Automate angular example deployment

- .github/workflows/bump-version.yml
- .github/workflows/deploy-angular-example.yml
- .github/workflows/pr-actions.yaml
> ci: Change node version from 16.x to 18.x in workflows

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v8.5.1` for all packages.
> chore: Bump version to v8.5.1

- examples/angular/src/app/components/content/content.component.ts
> Change modal-ui path into modal-ui-js in angular example

- .github/workflows/deploy-angular-example.yml
> Add permission to angular deploy workflow

- .github/workflows/bump-version.yml
- .github/workflows/dev-pr.yml
- .github/workflows/pr-actions.yaml
- nx.json
- packages/my-near-wallet/tsconfig.json
- Added `deploy` to `targetDefaults` on `nx.json` this way the dependencies are first built and deployed so the build errors will not show up.
- Changed the `deploy` command in `bump-version.yml` and added the `--noBuild` tag to remove the responsibility of building the packages from the `ngx-deploy-npm`
- Merged branch with main to align `dev` and `main`.
> fix: Fix build errors on deploy script

- packages/core/src/lib/helpers/verify-signature/verify-signature.ts
- Updated the verifySignature function so that it exactly matches the referenced example in the NEP0413 signMessage:
https://github.com/near/NEPs/blob/master/neps/nep-0413.md#references
https://github.com/gagdiez/near-login/blob/main/authenticate/wallet-authenticate.js#L17
- Verifies the signed message based on the example: 
https://github.com/gagdiez/near-login/blob/main/tests/authentication/wallet.ts#L60
- Added comments and changed variable names to more descriptive names.
> refactor: Update verifySignature based on NEP example

- README.md
- packages/finer-wallet/README.md
> docs: Removing finer wallet from Readme file

- .github/workflows/bump-version.yml
- Changed the way we run the `deploy` command from `yarn` to `npx`.
- Added a comment in the workflow file so we know why we're using `npx` here.
> fix: Fix deploy step in bump-version workflow

- package.json
- packages/here-wallet/src/lib/selector.ts
- packages/here-wallet/src/lib/types.ts
- yarn.lock
> fix: Add `signMessage` to HERE Wallet

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to v8.5.2 for all packages.
> chore: Bump version to v8.5.2

- .github/workflows/bump-version.yml
> ci: Add correct permissions in bump-version file

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to v8.5.3 for all packages.
> chore: Bump version to v8.5.3

- examples/README.md
- examples/angular/README.md
- examples/react/README.md
> docs: Added readme files documentation for examples ( Angular, React )

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to v8.5.4 for all packages.
> chore: Bump version to v8.5.4

- packages/my-near-wallet/src/lib/my-near-wallet.spec.ts
- packages/my-near-wallet/src/lib/my-near-wallet.ts
> feat: Add sign message support

- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
> feat: Add validation for required params for signMessage

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to v8.6.0

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly-connect/package.json
- packages/nightly/package.json
- packages/opto-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bump version to `v8.7.0` for all packages.
> chore: Bump version to v8.7.0

- packages/near-mobile-wallet/package.json
This PR aligns the version of NearMobileWallet with other packages.
- Bump version for NearMobileWallet to `v8.7.0`
> chore: Bump NearMobileWallet version to v8.7.0

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/default-wallets/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version to `v8.7.1` for all packages.
> chore: Bump version to v8.7.1

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bump version to `v8.7.2` for all packages.
> chore: Bump version to v8.7.2

- package.json
- yarn.lock
changes from https://github.com/Mintbase/mintbase-js/pull/434  by @kujtimprenkuSQA
> update to mintbase-wallet 0.5.0-beta.6

- package.json
- packages/account-export/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/finer-wallet/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bump version to `v8.8.0` for all packages.
> chore: Bump version to v8.8.0

- examples/README.md
> docs: Update examples docs

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bump version to `v8.9.1` for all packages.
> chore: Bump version to v8.9.1

- packages/wallet-connect/src/lib/wallet-connect-client.ts
> fix: Avoid creating walletconnect modal multiple times

- .gitignore
- nx.json
- Replace the NX cloud token with a new one that is `read-only`.
> fix: Create new NX cloud workspace

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version for all package to `v8.9.2`
> chore: Bump version to v8.9.2

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/near-wallet/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version for all package to `v8.9.3`
> chore: Bump version to v8.9.3

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version for all packages to `v8.9.4`
> chore: Bump version to v8.9.4

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- Bumped version for all packages to `v8.9.5`
> chore: Bump version to v8.9.5

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Updated version in all package.json files to 8.9.6.  Tests ran successfully on local machine.
> Chore: bump versions in all package.json files.

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Version bump to prep for release with #1107
> chore: Bump version 8.9.8

- README.md
- examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts
- examples/react/contexts/WalletSelectorContext.tsx
- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Bump version to 8.9.9, add OKX to the main README and use consistent wallet ordering in the examples.
> chore: Bump version 8.9.9 for OKX Wallet

- yarn.lock
Not sure how this got flubbed, but this should unflub it.
> fix: fix lockfile

- scripts/release-packages.bash
> fix: Adding OKX wallet package

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version 8.9.10

- README.md
> docs: remove duplicate `setupNearSnap`

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Chore bump version v8.9.11

- package.json
- packages/account-export/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: Bump version to 8.9.12

- package.json
- packages/here-wallet/src/index.ts
- packages/here-wallet/src/lib/index.ts
- packages/here-wallet/src/lib/selector.ts
- packages/here-wallet/src/lib/types.ts
- packages/modal-ui/src/lib/components/WalletOptions.tsx
- yarn.lock
> chore: [fix] - here wallet

- package.json
- yarn.lock
> chore: [bump] - @mintbase-js/wallet to 0.6.1 (near-api-js v4)

- packages/core/src/lib/locale/jp.json
> docs: add jp translation

- packages/bitget-wallet/README.md
Update the Bigget Wallet link to the latest version on the Chrome Web Store, ensuring that users are directed to the correct page without encountering any additional redirects.
> docs: update README.md

- README.md
Supported wallets are now sorted alphabetically for easier and more convenient browsing.
> docs: supported wallets are sorted alphabetically

- package.json
- packages/account-export/package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> Bump version to v8.9.14

- package.json
- packages/account-export/package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet/package.json
- packages/mintbase-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nearfi/package.json
- packages/neth/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore-bump-version-v8.9.15

- packages/core/src/lib/locale/hu.json
- packages/core/src/lib/locale/it.json
Add it and hu translations #1200
> Add it and hu translations

- packages/core/src/lib/locale/pt.json
> Add pt translation

- package.json
- packages/hot-wallet/src/lib/index.ts
- yarn.lock
> feat: hot-wallet

- packages/react-hook/package.json
> chore: package dependencies

- scripts/release-package-public.bash
> feat: Added script for easy publish of packages to set scope public

- examples/react/components/Content.tsx
- examples/react/pages/index.tsx
- examples/react/wallets/web3modal.ts
- packages/core/src/lib/constants.ts
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- packages/core/src/lib/store.ts
- packages/core/src/lib/store.types.ts
- packages/core/src/lib/wallet-selector.ts
- packages/core/src/lib/wallet-selector.types.ts
- packages/react-hook/src/lib/WalletSelectorProvider.tsx
Initialize wallets async so they don't block the whole wallet selector
> Async modules init

- .github/workflows/add-to-devtools.yml
> fix: update gh project token

- package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/hot-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet-app/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/react-hook/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
- yarn.lock
Updated versions to 9.0.0-beta.0 against v9-beta branch
> Chore: bump beta version for v9-beta.

- package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/hot-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet-app/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/react-hook/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
Chore: bump version for v9.0.0-beta.1
> chore: bump version for v9.0.0-beta.1

- package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/hot-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet-app/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/react-hook/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: chore-bump-version-v9.0.0

- package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/hot-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet-app/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/react-hook/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: chore-bump-version-v9.0.1

- package.json
- packages/arepa-wallet/package.json
- packages/bitget-wallet/package.json
- packages/bitte-wallet/package.json
- packages/coin98-wallet/package.json
- packages/core/package.json
- packages/ethereum-wallets/package.json
- packages/here-wallet/package.json
- packages/hot-wallet/package.json
- packages/intear-wallet/package.json
- packages/ledger/package.json
- packages/math-wallet/package.json
- packages/meteor-wallet-app/package.json
- packages/meteor-wallet/package.json
- packages/modal-ui-js/package.json
- packages/modal-ui/package.json
- packages/my-near-wallet/package.json
- packages/narwallets/package.json
- packages/near-mobile-wallet/package.json
- packages/near-snap/package.json
- packages/nightly/package.json
- packages/okx-wallet/package.json
- packages/ramper-wallet/package.json
- packages/react-hook/package.json
- packages/sender/package.json
- packages/wallet-connect/package.json
- packages/wallet-utils/package.json
- packages/welldone-wallet/package.json
- packages/xdefi/package.json
> chore: chore-bump-version-v9.0.2

- package.json
- packages/arepa-wallet/src/lib/arepa-wallet.ts
- packages/bitget-wallet/src/lib/bitget-wallet.ts
- packages/coin98-wallet/src/lib/coin98-wallet.ts
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- packages/core/src/lib/wallet/wallet.types.ts
- packages/ethereum-wallets/src/lib/index.ts
- packages/here-wallet/src/lib/selector.ts
- packages/hot-wallet/src/lib/index.ts
- packages/intear-wallet/src/lib/intear-wallet.ts
- packages/ledger/src/lib/ledger.spec.ts
- packages/ledger/src/lib/ledger.ts
- packages/math-wallet/src/lib/math-wallet.ts
- packages/meteor-wallet-app/src/lib/meteor-wallet-app.ts
- packages/meteor-wallet/src/lib/meteor-wallet.ts
- packages/my-near-wallet/src/lib/my-near-wallet.ts
- packages/narwallets/src/lib/narwallets.ts
- packages/near-mobile-wallet/src/lib/init.wallet.ts
- packages/near-snap/src/lib/selector.ts
- packages/nightly/src/lib/nightly.ts
- packages/okx-wallet/src/lib/okx-wallet.ts
- packages/ramper-wallet/src/lib/ramper-wallet.ts
- packages/sender/src/lib/sender.ts
- packages/wallet-connect/src/lib/wallet-connect.ts
- packages/welldone-wallet/src/lib/welldone.ts
- packages/xdefi/src/lib/xdefi.ts
- yarn.lock
> Implement `Signer` interface for core `Wallet` and adapters

- .changeset/calm-foxes-build.md
- .changeset/empty-vans-stick.md
- .changeset/silly-mice-worry.md
- .changeset/weak-games-fly.md
- packages/unity-wallet/package.json
> Add changeset for #1361

- .changeset/slick-hoops-clean.md
- .changeset/whole-dragons-sniff.md
- .github/dependabot.yml
- CONTRIBUTING.md
- packages/bitget-wallet/src/lib/bitget-wallet.ts
- packages/core/jest.config.js
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.spec.ts
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- packages/core/src/lib/store.ts
- packages/core/src/lib/store.types.ts
- packages/core/src/lib/testUtils.ts
- packages/core/src/lib/wallet-selector.ts
- packages/hot-wallet/README.md
- packages/narwallets/src/lib/narwallets.ts
- packages/nightly/src/lib/nightly.ts
- packages/okx-wallet/src/lib/okx-wallet.ts
- packages/sender/src/lib/sender.ts
- packages/welldone-wallet/src/lib/welldone.ts
- packages/xdefi/src/lib/xdefi.ts
This PR refactors the WalletModules service to improve its architecture, maintainability, and testability. The motivation includes:
1. **Better separation of concerns**: The original \`setup()\` method was doing too many things. Splitting it into \`setupWalletModules()\` and \`setupStorage()\` makes the code more modular and easier to test
2. **Improved instance caching**: The wallet instance management was inefficient, potentially creating duplicate instances. The refactored approach ensures proper caching
3. **Enhanced type safety**: Removed unnecessary \`SignMessageMethod\` dependencies from type signatures to simplify the type system
4. **Comprehensive test coverage**: Added a complete test suite (505 lines) to ensure reliability and prevent regressions
5. **Code organization**: …
> refactor(core): improve WalletModules service architecture and add comprehensive tests

- .changeset/three-coins-attend.md
- package.json
- packages/meteor-wallet/jest.config.ts
- packages/meteor-wallet/package.json
- pnpm-lock.yaml
> fix: update meteor sdk

- .changeset/brown-lamps-dress.md
- examples/react/pages/index.tsx
- packages/core/README.md
- packages/core/docs/api/selector.md
- packages/core/src/lib/options.spec.ts
- packages/core/src/lib/options.ts
- packages/core/src/lib/options.types.ts
- packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts
- packages/core/src/lib/wallet-selector.types.ts
- packages/react-hook/README.md
- packages/react-hook/src/lib/WalletSelectorProvider.tsx
Revert #1362 due to interface breaking. Will include these changes in the major upgrade instead
> fix: revert breaking interface

- README.md
> chore: fixed broken link Guest Book
